runtime: go122
instance_class: F1
service: expenses-api
env_variables:
  ENV: "production"
  PORT: "8080"
  DEBUG: "false"
  LOG_LEVEL: "info"
  DB_DSN: "quotes-user:M9@I*49e2b#9Ek}_@unix(/cloudsql/quotes-api-100:us-east1:quotes-instance)/expenses_db?charset=utf8mb4&parseTime=True&loc=Local"
  CORS_ALLOWED_ORIGIN: "*"
  JWT_SECRET: "expenses-api-production-secret-2024"
beta_settings:
  cloud_sql_instances: "quotes-api-100:us-east1:quotes-instance"
automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65
